### ISSUE TITLE
A few housekeeping items

### ISSUE THREAD

**Issue by cantchooseausername** [groogiam/project-chadrick#1]
Found a few issues that we might want clean up: 
- Sort burns with the most recent at the top instead of first burn
- If there are no additional burns to display, hide the "Load more..." button
- Should we add a message saying there are no burns to display if there are no burns to display?
- The submit button in the post burn section isn't active until after you click away from the description box. Do we want to fix that, or leave it as validation?
- When all burns are displayed, if I continue clicking "Load more..." it keeps adding the last few burns onto the list even though they're already displayed

**Comment by groogiam** [comment]
Hiding or disabling he load more button is a bit problematic as burns posted by someone else will not be able to be able to reenable it without implementing some sort of polling mechanism. Leaving this as is but I will fix the burn order and Load More displaying too many entries issue.
